# Generated by Django 3.0.3 on 2020-07-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200729_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='amount',
            field=models.IntegerField(default=20),
        ),
    ]
